### ISSUE TITLE
WASM Source

### ISSUE THREAD

**Issue by mdjp** [RouganStriker/IceColdBeer#1]
Hi, I am putting together a leaving gift for a colleague which is a hardware version of this game (but using an emulator). I came across this repo and it looks like it is just what we need.  I just wondered where the original code came from as I would really like to make a few changes to personalise the app, but have been struggling to find anything other that binaries.  Any help would be much appreciated.

**Comment by RouganStriker** [comment]
I asked my friend about the source code and she has made it available here: https://github.com/MichelleFuncke/ArcadeGame
Hope it goes well!

**Comment by mdjp** [comment]
Amazing, thank you both so much.
